### ISSUE TITLE
about dataset 

### ISSUE THREAD

**Issue by likemac12138** [XuRobotics/slide-slam#1]
dear author，
i'm very interested in your github.com/XuRobotics/lidar-bonnetal, and trying to train the lidar-bonnetal network , but when i trying to download the data from the link https://drive.google.com/drive/folders/16MSQf-tdD1QTYpVVtElMy1enAQv7hFAR?usp=sharing and https://drive.google.com/drive/folders/1x93D_17G6UyWZoD7NvXacXGUzZZ6G2Wi?usp=sharing, I don't have permission to access your data files , can i get the permission to access the forest and pennovation data files ?
Thanks for your kindly help sincerely !

**Comment by XuRobotics** [comment]
Thanks for your interest. I have shared the example pennovation data files with you.
